import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ilham Iyadillah</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Inter&family=Lato:wght@300&display=swap" rel="stylesheet"></link> */}
      </Head>
      {/* profile */}
      <div id="inter" className="container flex flex-col lg:flex-row bg-gray-200 h-screen w-screen text-black ">
        {/* left */}
        <div className="hidden xl:flex flex-col items-center justify-center w-full h-full">
          <div id="ppbox" className="border-4 -mt-26 rounded-full bg-gradient-to-r from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]">
            <Image alt="ilham iyadillah" src="/img/remove.png" layout="fill" objectFit="cover" />
          </div>
          <div className="mb-10 pt-10">
            <h1 id="lato" className="text-black text-4xl font-semibold">
              Frontend Developer
            </h1>
            <div className="flex flex-row gap-5 justify-center mt-16">
              <a href="https://www.instagram.com/ilham.i7/" className="w-fit">
                <Image alt="instagram" src="/img/insta.png" width={30} height={30} />
              </a>
              <a href="https://www.linkedin.com/in/hiyadillah/" className="w-fit">
                <Image alt="linkedin" src="/img/linkedin.png" width={30} height={30} />
              </a>
            </div>
          </div>
        </div>
        {/* right */}
        <div className="flex flex-col pl-24 pt-24 bg-sky-900 font-sans text-white w-full pr-16 lg:h-full h-screen">
          {/* photo in mobile */}
          <div className="flex flex-col xl:hidden mb-16">
            <div id="ppbox" className="mx-auto -mt-26 rounded-full bg-gradient-to-r from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]">
              <Image alt="ilham iyadillah" src="/img/remove.png" layout="fill" objectFit="cover" />
            </div>
            <div className="flex flex-col items-center mb-10 pt-10">
              <h1 id="lato" className="text-white text-4xl font-semibold ">
                Frontend Developer
              </h1>
              <div className="flex flex-row gap-5 justify-center mt-16">
                <a href="https://www.instagram.com/ilham.i7/" className="w-fit">
                  <Image alt="instagram" src="/img/insta.png" width={30} height={30} />
                </a>
                <a href="https://www.linkedin.com/in/hiyadillah/" className="w-fit">
                  <Image alt="linkedin" src="/img/linkedin.png" width={30} height={30} />
                </a>
              </div>
            </div>
          </div>
          <div className="flex mb-16  text-9xl font-bold drop-shadow-2xl">Hello!</div>
          <div className="flex text-5xl mb-16 font-semibold">
            I&apos;M
            <span className="pl-5 text-yellow-500 " id="lato">
              Ilham Iyadillah
            </span>
          </div>
          <div className="flex ">
            <p className="text-xl font-semibold text-justify">
              Im an active student in IPB University semester 7th. I love to build elegant and functional website. Currently interest in react framework and game development. i have softskill consist of leadership in computer science
              student club and teamwork in startup company “imperio fish”.
            </p>
          </div>
        </div>
      </div>
      {/* work */}
      <div className="container bg-gray-200 w-screen text-sky-900 h-fit pb-24">
        <div className="flex flex-col ">
          <div className="h-5 bg-gradient-to-r from-sky-900 m-16"></div>
          <div className="flex justify-center w-full h-6/12 py-10">
            <h1 className="text-7xl font-bold">My Work</h1>
          </div>
          <div className="grid xl:grid-cols-2 justify-evenly lg:flex-col">
            {/* gambar pertama */}
            <div className="flex flex-col justify-center mt-16 mx-16 ">
              <div id="boxwork">
                <Image className="" src="/img/Imperiofish.png" layout="fill" objectFit="contain" alt="Gambar Web Proyek Imperiofish" />
              </div>
              <div id="inter" className="flex flex-col justify-center my-5 ">
                <h1 className="text-xl self-center">Imperiofish</h1> <br />
                <div className="text-black mx-auto  my-5">
                  <span className="">
                    Role: Frontend <br /> Framework : React, Laravel <br /> Fitur : <br />
                  </span>
                  <lo>
                    <li>Search</li>
                    <li>Profile Management (Password, biodata)</li>
                  </lo>
                </div>
              </div>
            </div>
            {/* gambar kedua */}
            <div className="flex flex-col justify-center mt-16 mx-16 ">
              <div id="boxwork">
                <Image className="" src="/img/LinkedOn.png" layout="fill" objectFit="contain" alt="Gambar Web Proyek LinkedOn" />
              </div>
              <div id="inter" className="flex flex-col justify-center my-5 ">
                <h1 className="text-xl self-center">LinkedOn</h1> <br />
                <div className="text-black mx-auto my-5">
                  <span>
                    Role: Frontend <br /> Framework : Laravel <br /> Fitur : <br />
                  </span>
                  <lo>
                    <li>CRDUD</li>
                    <li>Search</li>
                    <li>Profile Management (Password, biodata)</li>
                  </lo>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
